title: Thomas Lauber
logo: /assets/img/profile_hex.png
description: Geospatial Data Scientist | Ecologist
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: BDHU/minimalist


# extra_info: |
#   - ğŸŒ Geospatial Developer  
#   - ğŸŒ² Forest Ecology Enthusiast  
#   - ğŸ“ Based in XYZ


include: ["_includes"]


