title: Thomas Lauber
logo: /assets/img/profilePic.jpeg
description: Geospatial Data Scientist | Ecologist
# show_downloads: true
theme: jekyll-theme-minimal

extra_info: |
  - ğŸŒ Geospatial Developer  
  - ğŸŒ² Forest Ecology Enthusiast  
  - ğŸ“ Based in XYZ
